/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.Mycontroller;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import model.NhanVien;

/**
 *
 * @author NGUYEN MINH
 */
public class QLNV_SuaNhanVien extends javax.swing.JFrame {
    private static Mycontroller controller = new Mycontroller();
    private static List<NhanVien> nvList = controller.readDataFromFile("src/file/nhanvien.txt");
    private static int index;
    SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
    /**
     * Creates new form QuanLyNhanVien
     */
    public QLNV_SuaNhanVien(int index) {
        this.index = index;
        initComponents();
        setLocationRelativeTo(null);
        lbValueMaNV.setText(nvList.get(index).getMaNV());
        lbValueNgayVaoLam.setText(dateFormat.format(nvList.get(index).getNgayVaoLam()));
    }

    QLNV_SuaNhanVien(TrangChu aThis, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSua = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        txtTenNV = new javax.swing.JTextField();
        lbTenNV = new javax.swing.JLabel();
        lbSDT = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        lbDiaChi = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        lbNgayVaoLam = new javax.swing.JLabel();
        lbValueMaNV = new javax.swing.JLabel();
        lbMaNV1 = new javax.swing.JLabel();
        lbValueNgayVaoLam = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("SỬA THÔNG TIN NV");

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnHuy.setText("Huỷ");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        txtTenNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenNVActionPerformed(evt);
            }
        });

        lbTenNV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbTenNV.setText("Tên NV");

        lbSDT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbSDT.setText("Số điện thoại");

        txtSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDTActionPerformed(evt);
            }
        });

        lbDiaChi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbDiaChi.setText("Địa chỉ");

        txtDiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaChiActionPerformed(evt);
            }
        });

        lbNgayVaoLam.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNgayVaoLam.setText("Ngày vào làm");

        lbValueMaNV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbValueMaNV.setText("Mã NV");

        lbMaNV1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbMaNV1.setText("Mã NV");

        lbValueNgayVaoLam.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbValueNgayVaoLam.setText("Mã NV");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNgayVaoLam)
                            .addComponent(lbDiaChi)
                            .addComponent(lbSDT)
                            .addComponent(lbTenNV)
                            .addComponent(lbMaNV1))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbValueMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbValueNgayVaoLam, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel1)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbValueMaNV)
                    .addComponent(lbMaNV1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTenNV)
                    .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSDT)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDiaChi)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNgayVaoLam)
                    .addComponent(lbValueNgayVaoLam))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSua)
                    .addComponent(btnHuy))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        List<NhanVien> list = controller.readDataFromFile("src/file/nhanvien.txt");
        String maNV = lbValueMaNV.getText();
        String tenNV = txtTenNV.getText();
        String sdt = txtSDT.getText();
        String diaChi = txtDiaChi.getText();
        String ngayVaoLamString = lbValueNgayVaoLam.getText();
        Date ngayVaoLam = null;
        try {
            ngayVaoLam = dateFormat.parse(ngayVaoLamString);
        } catch (ParseException ex) {
            Logger.getLogger(QLNV_SuaNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String regex = "^0\\d{9}$";
        Pattern pattern = Pattern.compile(regex);
        Matcher SDTmatcher = pattern.matcher(sdt);
        
        try {
            if (maNV.isEmpty() || tenNV.isEmpty() || sdt.isEmpty() || diaChi.isEmpty() || ngayVaoLamString.isEmpty()) {
                JOptionPane.showConfirmDialog(this, "Vui lòng điền đủ thông tin của form", "Lỗi", JOptionPane.OK_OPTION);
                throw new Exception("Khong dien du thong tin yeu cau");
            } else {
                if (!SDTmatcher.matches()) {
                    JOptionPane.showMessageDialog(this, "Vui lòng điền số điện thoại gồm 10 số, bắt đầu bằng 0", "Số điện thoại sai định dạng", JOptionPane.ERROR_MESSAGE);
                    new QLNV_SuaNhanVien(index).setVisible(true);
                    this.dispose();
                    return;
                }
                NhanVien nvDaSua = new NhanVien(maNV, tenNV, sdt, diaChi, ngayVaoLam);
                list.set(index, nvDaSua);
                controller.writeToFile(list, "src/file/nhanvien.txt");
                new QuanLyNhanVien().setVisible(true);
                this.dispose();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
            
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        new QuanLyNhanVien().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHuyActionPerformed

    private void txtTenNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenNVActionPerformed

    private void txtSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSDTActionPerformed

    private void txtDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaChiActionPerformed

    public void displayDetails(String tenNV, String SDT, String diaChi) {
        txtTenNV.setText(tenNV);
        txtSDT.setText(SDT);
        txtDiaChi.setText(diaChi);      
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLNV_SuaNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLNV_SuaNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLNV_SuaNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLNV_SuaNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLNV_SuaNhanVien(index).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnSua;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbDiaChi;
    private javax.swing.JLabel lbMaNV1;
    private javax.swing.JLabel lbNgayVaoLam;
    private javax.swing.JLabel lbSDT;
    private javax.swing.JLabel lbTenNV;
    private javax.swing.JLabel lbValueMaNV;
    private javax.swing.JLabel lbValueNgayVaoLam;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenNV;
    // End of variables declaration//GEN-END:variables
}
