/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.Mycontroller;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.PhieuXuat;

/**
 *
 * @author ACER
 */
public class QLPX_TimKiem extends javax.swing.JFrame {

    /**
     * Creates new form QLPX_TimKiem
     */
    public QLPX_TimKiem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_tnv = new javax.swing.JButton();
        btn_tkh = new javax.swing.JButton();
        label_timkiem = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_timkiem = new javax.swing.JTable();
        btn_trove = new javax.swing.JButton();
        btn_timkiem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_tnv.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_tnv.setText("TÊN NHÂN VIÊN");
        btn_tnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tnvActionPerformed(evt);
            }
        });

        btn_tkh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_tkh.setText("TÊN KHÁCH HÀNG");
        btn_tkh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tkhActionPerformed(evt);
            }
        });

        label_timkiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_timkiem.setText("Nhập tên nhân viên: ");

        table_timkiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phiếu xuất", "Ngày xuất", "Số lượng xuất", "Giá bán", "Tên khách hàng", "Tên nhân viên"
            }
        ));
        table_timkiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_timkiemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_timkiem);

        btn_trove.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_trove.setText("TRỞ VỀ");
        btn_trove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_troveActionPerformed(evt);
            }
        });

        btn_timkiem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_timkiem.setText("TÌM KIẾM");
        btn_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("TÌM KIẾM THEO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_trove)
                        .addGap(144, 144, 144)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(label_timkiem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btn_timkiem)))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_tnv)
                .addGap(44, 44, 44)
                .addComponent(btn_tkh)
                .addGap(153, 153, 153))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_trove)
                    .addComponent(jLabel1))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tnv)
                    .addComponent(btn_tkh))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_timkiem)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_timkiem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void table_timkiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_timkiemMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_table_timkiemMouseClicked

    private void btn_tkhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tkhActionPerformed
        label_timkiem.setText("Nhập tên khách hàng: ");
    }//GEN-LAST:event_btn_tkhActionPerformed

    private void btn_tnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tnvActionPerformed
        // TODO add your handling code here:
        label_timkiem.setText("Nhập tên nhân viên: ");
    }//GEN-LAST:event_btn_tnvActionPerformed

    private void btn_troveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_troveActionPerformed
        // TODO add your handling code here:
        new QuanLyPhieuXuat().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_troveActionPerformed

    private void btn_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemActionPerformed
        Mycontroller controller = new Mycontroller();
        List<PhieuXuat> listpx = controller.readDataFromFile("src/file/phieuxuat.txt");
        List<PhieuXuat> listpxtk = new ArrayList<>();
        DefaultTableModel modellpxtk = (DefaultTableModel) table_timkiem.getModel();
        if(label_timkiem.getText() == "Nhập tên nhân viên: "){
            for(PhieuXuat px: listpx){
                if(txtTimKiem.getText().equals(px.getTenNV())){
                    listpxtk.add(px);
                }
            }
            if(listpxtk.size() == 0){
                JOptionPane.showMessageDialog(this, "Không tìm thấy phiếu xuất!","Thông báo",1);
            }
            else{
                this.showData(listpxtk, modellpxtk);
            }
        }
        else if(label_timkiem.getText() == "Nhập tên khách hàng: "){
            for(PhieuXuat px:listpx){
                if(txtTimKiem.getText().equals(px.getTenKhachHang())){
                    listpxtk.add(px);
                }   
            }
            if(listpxtk.size() == 0){
                JOptionPane.showMessageDialog(this, "Không tìm thấy phiếu xuất có tên khách hàng!","Thông báo", 1);
            }
            else{
                this.showData(listpxtk, modellpxtk);
            }
        }
    }//GEN-LAST:event_btn_timkiemActionPerformed
        private void showData(List<PhieuXuat> list, DefaultTableModel model){
        try{
            model.setRowCount(0);
            for(PhieuXuat px : list){
                model.addRow(new Object[]
                {
                    px.getMaPhieuXuat(),
                    px.getNgayXuat(),
                    px.getSoLuongXuat(),
                    px.getGiaBan(),
                    px.getTenKhachHang(),
                    px.getTenNV(),
                });
            }
        }
        catch(Exception ex){
            System.out.println("Loi la : " + ex.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLPX_TimKiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLPX_TimKiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLPX_TimKiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLPX_TimKiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLPX_TimKiem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_timkiem;
    private javax.swing.JButton btn_tkh;
    private javax.swing.JButton btn_tnv;
    private javax.swing.JButton btn_trove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_timkiem;
    private javax.swing.JTable table_timkiem;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
