/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.Mycontroller;
import model.PhieuXuat;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author ACER
 */
public class QLPX_Sua extends javax.swing.JFrame {

    private static Mycontroller controller = new Mycontroller();
    private static List<PhieuXuat> listpx = controller.readDataFromFile("src/file/phieuxuat.txt");
    private static int indexTB;
    public QLPX_Sua() {
        initComponents();
        this.setTitle("Sửa thông tin phiếu xuất");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNMPX = new javax.swing.JTextField();
        txtNNX = new javax.swing.JTextField();
        txtNSLX = new javax.swing.JTextField();
        txtNGB = new javax.swing.JTextField();
        txtNTKH = new javax.swing.JTextField();
        txtNTNV = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        BTN_CAPNHAT = new javax.swing.JButton();
        BTN_HUY = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("SỬA PHIẾU XUẤT");

        txtNMPX.setEditable(false);
        txtNMPX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNMPXActionPerformed(evt);
            }
        });

        txtNNX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNNXActionPerformed(evt);
            }
        });

        txtNTKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNTKHActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Mã phiếu xuất:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Ngày xuất:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Số lượng xuất:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Giá bán: ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Tên khách hàng:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Tên nhân viên:");

        BTN_CAPNHAT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BTN_CAPNHAT.setText("CẬP NHẬT");
        BTN_CAPNHAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_CAPNHATActionPerformed(evt);
            }
        });

        BTN_HUY.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BTN_HUY.setText("HỦY BỎ");
        BTN_HUY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_HUYActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNGB, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNNX)
                            .addComponent(txtNSLX)
                            .addComponent(txtNTKH)
                            .addComponent(txtNTNV)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNMPX, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BTN_CAPNHAT)
                        .addGap(78, 78, 78)
                        .addComponent(BTN_HUY, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNMPX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNNX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNSLX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNGB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNTKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNTNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_CAPNHAT)
                    .addComponent(BTN_HUY))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNMPXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNMPXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNMPXActionPerformed

    private void txtNNXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNNXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNNXActionPerformed

    private void txtNTKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNTKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNTKHActionPerformed

    private void BTN_CAPNHATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_CAPNHATActionPerformed
        // TODO add your handling code here:
        String mapx = txtNMPX.getText();
        String nx = txtNNX.getText();
        String SL = txtNSLX.getText();
        String gb = txtNGB.getText();
        String TKH = txtNTKH.getText();
        String TNV = txtNTNV.getText();
        
        PhieuXuat px = new PhieuXuat(mapx, nx, SL, TKH, TNV, gb);
        try{
            if(nx.isEmpty()){
                JOptionPane.showConfirmDialog(this, "Không được để trống ngày xuất!");
                throw new Exception("Lỗi trống ngày xuất!");
            }
            else if(SL.isEmpty()){
                JOptionPane.showConfirmDialog(this, "Không được để trống số lượng xuất!");
                throw new Exception("Lỗi trống số lượng xuất!");
            }
            else if(gb.isEmpty()){
                JOptionPane.showConfirmDialog(this, "Không được để trống giá bán!");
                throw new Exception("Lỗi trống số giá bán!");
            }
            else if(TKH.isEmpty()){
                JOptionPane.showConfirmDialog(this, "Không được để trống tên khách hàng!");
                throw new Exception("Lỗi trống tên khách hàng!");
            }
            else if(TNV.isEmpty()){
                JOptionPane.showConfirmDialog(this, "Không được để trống tên nhân viên!");
                throw new Exception("Lỗi trống tên nhân viên!");
            }
            else {
                listpx.set(indexTB, px);
                controller.writeToFile(listpx, "src/file/phieuxuat.txt");
                new QuanLyPhieuXuat().setVisible(true);
                this.dispose();
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_BTN_CAPNHATActionPerformed
    public void displayDetails(int position, String mapx, String nx, String SLX,String GB,String TKH, String TNV){
        txtNMPX.setText(mapx);
        txtNNX.setText(nx);
        txtNSLX.setText(SLX);
        txtNGB.setText(GB);
        txtNTKH.setText(TKH);
        txtNTNV.setText(TNV);
        indexTB = position;
    }
    private void BTN_HUYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_HUYActionPerformed
        // TODO add your handling code here:
        new QuanLyPhieuXuat().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTN_HUYActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLPX_Sua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLPX_Sua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLPX_Sua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLPX_Sua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLPX_Sua().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_CAPNHAT;
    private javax.swing.JButton BTN_HUY;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtNGB;
    private javax.swing.JTextField txtNMPX;
    private javax.swing.JTextField txtNNX;
    private javax.swing.JTextField txtNSLX;
    private javax.swing.JTextField txtNTKH;
    private javax.swing.JTextField txtNTNV;
    // End of variables declaration//GEN-END:variables
}
