/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.Mycontroller;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.PhieuXuat;

/**
 *
 * @author ACER
 */
public class QuanLyPhieuXuat extends javax.swing.JFrame {

    //public static ArrayList<PhieuXuat> ListPX = new ArrayList<>();
    private static DefaultTableModel modelPX;
    private static Mycontroller controller = new Mycontroller();
    public QuanLyPhieuXuat() {
        List<PhieuXuat> listpx = controller.readDataFromFile("src/file/phieuxuat.txt");
        initComponents();
        setLocationRelativeTo(null);
        modelPX = (DefaultTableModel) tablepx.getModel();
        this.showData(listpx, modelPX);
        this.setTitle("Quản lý phiếu xuất");
    }   
    QuanLyPhieuXuat(TrangChu aThis, boolean b){
        throw new UnsupportedOperationException("Not supported yet!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMaPX = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNgayXuat = new javax.swing.JTextField();
        txtSoLuongXuat = new javax.swing.JTextField();
        txtTenKhachHang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTenNhanVien = new javax.swing.JTextField();
        btn_Them = new javax.swing.JButton();
        btn_Sua = new javax.swing.JButton();
        btn_Xoa = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablepx = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtGiaBan = new javax.swing.JTextField();
        btn_timkiem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(752, 427));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("QUẢN LÝ PHIẾU XUẤT");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Mã phiếu xuất: ");

        txtMaPX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaPXActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Ngày xuất: ");

        txtTenKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenKhachHangActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Số lượng xuất:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Tên khách hàng:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Tên nhân viên:");

        txtTenNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenNhanVienActionPerformed(evt);
            }
        });

        btn_Them.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Them.setText("THÊM");
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });

        btn_Sua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Sua.setText("SỬA");
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });

        btn_Xoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Xoa.setText("XÓA");
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });

        btn_exit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_exit.setText("TRỞ VỀ");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        tablepx.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phiếu xuất", "Ngày xuất", "Số lượng xuất", "Giá bán", "Tên khách hàng", "Tên nhân viên"
            }
        ));
        tablepx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablepxMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablepx);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Giá bán:");

        txtGiaBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaBanActionPerformed(evt);
            }
        });

        btn_timkiem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_timkiem.setText("TÌM KIẾM");
        btn_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(174, 174, 174)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtMaPX, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                                .addComponent(txtNgayXuat)
                                .addComponent(txtSoLuongXuat))
                            .addComponent(txtTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_Xoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Them, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Sua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_timkiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(57, 57, 57))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btn_exit))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaPX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Them))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNgayXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btn_Sua))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSoLuongXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Xoa))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(btn_timkiem))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTenKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenKhachHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenKhachHangActionPerformed

    private void txtTenNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenNhanVienActionPerformed
    public PhieuXuat getPX(){
        PhieuXuat px = new PhieuXuat();
        px.setMaPhieuXuat(txtMaPX.getText().trim());
        px.setSoLuongXuat(txtSoLuongXuat.getText().trim());
        px.setTenKhachHang(txtTenKhachHang.getText().trim());
        px.setTenNV(txtTenNhanVien.getText().trim());
        px.setNgayXuat(txtNgayXuat.getText().trim());
        px.setGiaBan(txtGiaBan.getText().trim());
        return px;
    }
 /*   public void hienthidulieubang(){
        DefaultTableModel tbModel = (DefaultTableModel)table_px.getModel();
        tbModel.setRowCount(0); // clear table
        for(PhieuXuat px: ListPX){
            Object [] rowData = new Object[6];
            rowData[0] = px.getMaPhieuXuat();
            rowData[1] = new SimpleDateFormat("dd/MM/yyyy").format(px.getNgayXuat());
            rowData[2] = px.getSoLuongXuat();
            rowData[3] = px.getGiaBan();
            rowData[4] = px.getTenKhachHang();
            rowData[5] = px.getTenNV();
            tbModel.addRow(rowData);
        }
    }*/
    private void showData(List<PhieuXuat> list, DefaultTableModel model){
        try{
            model.setRowCount(0);
            for(PhieuXuat px : list){
                model.addRow(new Object[]
                {
                    px.getMaPhieuXuat(),
                    px.getNgayXuat(),
                    px.getSoLuongXuat(),
                    px.getGiaBan(),
                    px.getTenKhachHang(),
                    px.getTenNV(),
                });
            }
        }
        catch(Exception ex){
            System.out.println("Loi la : " + ex.getMessage());
        }
    }
    
    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        String mapx = txtMaPX.getText();
        String ngayxuat = txtNgayXuat.getText();
        String soluong = txtSoLuongXuat.getText();
        String giaban = txtGiaBan.getText();
        String tennv = txtTenNhanVien.getText();
        String tenKH = txtTenKhachHang.getText();
        List<PhieuXuat> listPX = controller.readDataFromFile("src/file/phieuxuat.txt");
        try{
            if(mapx.isEmpty()){
                JOptionPane.showMessageDialog(this, "Vui lòng nhập mã phiếu xuất!","Lỗi",JOptionPane.OK_OPTION);
                throw new Exception("Lỗi trống mã phiếu xuất!");
            }
            else if(ngayxuat.isEmpty()){
                JOptionPane.showMessageDialog(this, "Không được để trống ngày xuất","Lỗi",JOptionPane.OK_OPTION);
                throw new Exception("Lỗi trống ngày xuất!");
            }
            else if(ngayxuat.isEmpty()){
                JOptionPane.showMessageDialog(this, "Không được để trống ngày xuất","Lỗi",JOptionPane.OK_OPTION);
                throw new Exception("Lỗi trống ngày xuất!");
            }
            else if(soluong.isEmpty()){
                JOptionPane.showMessageDialog(this, "Không được để trống số lượng","Lỗi",JOptionPane.OK_OPTION);
                throw new Exception("Lỗi trống số lượng!");
            }
            else if(giaban.isEmpty()){
                JOptionPane.showMessageDialog(this, "Không được để trống giá bán","Lỗi",JOptionPane.OK_OPTION);
                throw new Exception("Lỗi trống giá bán!");
            }
            else if(tenKH.isEmpty()){
                JOptionPane.showMessageDialog(this, "Không được để trống tên khách hàng","Lỗi",JOptionPane.OK_OPTION);
                throw new Exception("Lỗi trống tên khách hàng!");
            }
            else if(tennv.isEmpty()){
                JOptionPane.showMessageDialog(this, "Không được để trống tên nhân viên","Lỗi",JOptionPane.OK_OPTION);
                throw new Exception("Lỗi trống nhân viên!");
            }
            else if(!checkma(mapx)){
                JOptionPane.showMessageDialog(this, "Mã phiếu đã tồn tại, hãy kiểm tra lại mã phiếu xuất!");
                throw  new Exception("Lỗi trùng mã phiếu xuất!");
            }
            else{
                PhieuXuat PX = new PhieuXuat(mapx, ngayxuat, soluong, tenKH, tennv, giaban);
                listPX.add(PX);
                controller.writeToFile(listPX, "src/file/phieuxuat.txt");
                new QuanLyPhieuXuat().setVisible(true);
                this.dispose();
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_ThemActionPerformed
    public boolean checkma(String mapx){
        List<PhieuXuat> listPX= controller.readDataFromFile("src/file/phieuxuat.txt");
        for(PhieuXuat px: listPX){
            if(mapx.equals(px.getMaPhieuXuat())){
                return false;
            }
        }
        return true;
    }
    public void resetForm(){
        txtMaPX.setText("");
        txtNgayXuat.setText("");
        txtSoLuongXuat.setText("");
        txtTenKhachHang.setText("");
        txtTenNhanVien.setText("");
        txtGiaBan.setText("");
    }
    public Boolean checkValidateForm(){
        if(txtMaPX.getText().isEmpty()||
            txtNgayXuat.getText().isEmpty()||
            txtSoLuongXuat.getText().isEmpty()||
            txtTenKhachHang.getText().isEmpty()||
            txtTenNhanVien.getText().isEmpty()||txtGiaBan.getText().isEmpty()){
            return false;
        }
        return true;
    }
    
    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        int selectRow = tablepx.getSelectedRow();
        try{
            List<PhieuXuat> listpx = controller.readDataFromFile("src/file/phieuxuat.txt");
            if(listpx.size() == 0){
                JOptionPane.showMessageDialog(this, "Chưa có phiếu xuất để sửa!");
            }
            else if(selectRow == -1 ){
                JOptionPane.showMessageDialog(this, "Hãy chọn 1 phiếu để sửa!");
            }
            else{
                DefaultTableModel model = (DefaultTableModel) tablepx.getModel();
                String mapx = (String) model.getValueAt(selectRow, 0);
                String nx = (String) model.getValueAt(selectRow, 1);
                String sl = (String) model.getValueAt(selectRow, 2);
                String gb = (String) model.getValueAt(selectRow, 3);
                String tkh = (String) model.getValueAt(selectRow, 4);
                String tnv = (String) model.getValueAt(selectRow, 5);
                QLPX_Sua Sua = new QLPX_Sua();
                int index = -1;
                int tmp = 0;
                for(PhieuXuat px: listpx){
                    if(px.getMaPhieuXuat().equals(mapx)){
                        index = tmp;
                    }
                    tmp++;
                }
                if(index != -1){
                    Sua.displayDetails(selectRow, mapx, nx, sl, gb, tkh, tnv);
                    Sua.setVisible(true);
                    this.dispose();
                }
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_SuaActionPerformed
/*    public int edit(PhieuXuat PXnew){
        for(PhieuXuat px: ListPX){
            if(px.getMaPhieuXuat().equalsIgnoreCase(PXnew.getMaPhieuXuat())){
                px.setNgayXuat(PXnew.getNgayXuat());
                px.setSoLuongXuat(PXnew.getSoLuongXuat());
                px.setTenKhachHang(PXnew.getTenKhachHang());
                px.setTenNV(PXnew.getTenNV());
                return 1;
            }
        }
        return -1;
    }
*/   
    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        // TODO add your handling code here:
        new TrangChu().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_exitActionPerformed

    private void txtMaPXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaPXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaPXActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        int indexremove = tablepx.getSelectedRow();
        List<PhieuXuat> listpx = controller.readDataFromFile("src/file/phieuxuat.txt");
        try{
            if(listpx.size() == 0){
                JOptionPane.showMessageDialog(this, "Chưa có phiếu xuất để xóa!");
            }
            else if(indexremove == -1 ){
                JOptionPane.showMessageDialog(this, "Hãy chọn 1 phiếu để xóa!");
            }
            else{
                int choice = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa phiếu xuất này","Message",JOptionPane.YES_NO_OPTION);
                if(choice == JOptionPane.YES_OPTION ){
                    listpx.remove(indexremove);
                    showData(listpx, modelPX);
                    controller.writeToFile(listpx, "src/file/phieuxuat.txt");
                }
                else{
                    return;
                }
            }
        }
        catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btn_XoaActionPerformed

    private void tablepxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablepxMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tablepxMouseClicked

    private void txtGiaBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaBanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaBanActionPerformed

    private void btn_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemActionPerformed
        new QLPX_TimKiem().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_timkiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhieuXuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhieuXuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhieuXuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhieuXuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new QuanLyPhieuXuat().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_timkiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablepx;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtMaPX;
    private javax.swing.JTextField txtNgayXuat;
    private javax.swing.JTextField txtSoLuongXuat;
    private javax.swing.JTextField txtTenKhachHang;
    private javax.swing.JTextField txtTenNhanVien;
    // End of variables declaration//GEN-END:variables

    
     
}
